name: Deploy to Self-Hosted

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted # self-hosted ランナーを指定
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and run docker-compose
        run: |
          docker compose build
          docker compose down
          docker compose up -d
